"""remove MessageRead model

Revision ID: f0e623c260ec
Revises: 53273722101a
Create Date: 2025-03-26 19:42:45.486288

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0e623c260ec'
down_revision: Union[str, None] = '53273722101a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_reads_id', table_name='message_reads')
    op.drop_table('message_reads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_reads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='message_reads_message_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='message_reads_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_reads_pkey')
    )
    op.create_index('ix_message_reads_id', 'message_reads', ['id'], unique=False)
    # ### end Alembic commands ###
